experiments:
  - seeds: [420]
    t_exclude: [1]
    dim: 66
    latent_dim: 32
    alpha: 1.0
    deepset: true
    time_bend: true
    whiten: False

    dataset_num: 2
    data_type: "pdb"                 # alanine dipeptide: "pdb"   "pdb_in"
    data_name: "pdb"                 # alanine dipeptide: "pdb"   "pdb_in"
    data_on_cluster: "GFM"
    save_address: "GFM\\traj"

    vae_epochs: 400
    epochs: 100

    unet_num_channels_bend: 128
    hidden_dims_bend: [128,128,128]
    hidden_dims_flow: [128,128,128]
    hidden_dim_deepset: [128,128,128]
    hidden_dims_encoder: [64,64,64]

    batch_size: 512

    vae_lr: 0.001
    spline_lr: 0.00001
    slow_lr: 0.001
