experiments:
  - seeds: [420]
    t_exclude: [1]
    dim: 66
    latent_dim: 32
    alpha: 1.0
    deepset: true
    time_bend: true
    whiten: False

    dataset_num: 2
    data_type: "ADC"                 # alanine dipeptide: "ADC"   "ADI"
    data_name: "alanine"                 # alanine dipeptide: "alanine"
    data_on_cluster: "C:\\Users\\Administrator\\Desktop\\GFM"
    save_address: "C:\\Users\\Administrator\\Desktop\\GFM\\traj"

    vae_epochs: 400

    epochs: 100  # 100

    unet_num_channels_bend: 128
    hidden_dims_bend: [128,128,128]
    hidden_dims_flow: [128,128,128]
    hidden_dim_deepset: [128,128,128]
    hidden_dims_encoder: [64,64,64]

    batch_size: 512   # alanine dipeptide: 512, toy data: 256

    vae_lr: 0.001
    spline_lr: 0.00001
    slow_lr: 0.001
