experiments:
  - seeds: [420]
    t_exclude: [1]
    dim: 2                # alanine dipeptide: 66;  muller brown: 2
    alpha: 1.0
    deepset: true
    time_spline: true
    whiten: False

    dataset_num: 2
    data_type: "muller"                 # alanine dipeptide: "ADC"   "ADI";  toy data: "muller"
    data_name: "muller"                 # alanine dipeptide: "alanine";  toy data: "muller"
    data_on_cluster: "C:\\Users\\Administrator\\Desktop\\GFM"
    save_address: "C:\\Users\\Administrator\\Desktop\\GFM\\traj"

    metric_epochs: 400

    epochs: 50

    unet_num_channels_spline: 128
    hidden_dims_spline: [128,128,128]
    hidden_dims_velocity: [128,128,128]
    hidden_dim_deepset: [128,128,128]
    kappa: 1.5
    n_centers: 100  # alanine dipeptide: 150, toy data: 100

    batch_size: 256   # alanine dipeptide: 512, toy data: 256

    spline_lr: 0.00001

    # reflow interation
    reflow: false
    reflow_num: 3   # reflow iteration number

    # resample interation
    resample: false
    resample_num: 3   # resample iteration number
    iter_epochs: 100
    batch_size_i: 200

    # Train method
    converge: true            # false is just for interleaving experiments
    direc: "unbidirectional"  # or "bidirectional"